### ISSUE TITLE
Auto-Apply after date selection

### ISSUE THREAD

**Issue by Way** [cswarb/ngx-aircal#15]
Really cool component, I like it very much.
The only thing I am missing is an auto-close function to tell the picker to close directly after selecting the end date.
Do you think it's possible to add this functionality?

**Comment by cswarb** [comment]
@Way That is a great idea. 

I'll make it a config option so it doesn't affect anyone's current implementation. Expect it within the next week.

Cheers.

**Comment by cswarb** [comment]
@Way I've released this feature now, so install the latest version (v1.1.0), add the autoApplyAndClose option, and you should be good to go.

My implementation notes are as follows:
When an end date is selected (or a start date if a start and end already exist), the date selection is applied automatically and the calendar is closed.

Let me know if you come across any issues. I will close this issue for now.

Thanks!
