### ISSUE TITLE
How to increase size of input field and of the calendar

### ISSUE THREAD

**Issue by idomiralin** [cswarb/ngx-aircal#22]
Is there any way to increase the input field size?

Is there any way to increase the size of the calendar? I have tried with width and height in options, but it is not displayed correctly.

**Comment by cswarb** [comment]
@idomiralin Yes you can customise everything, but the only way to do this is to overwrite the styles with your own custom scss/css file.

You can use the default one included in Angular (style.scss), and include your custom styles in there as an example. Target the selectors of the calendar by using inspect element in the browser to find what you want to style..

The width/height options supplied only affect the opened calendar container.
